# Generated by Django 4.1 on 2022-08-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='phone_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
